kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "activemq-build"
spec:
  runPolicy: "Serial"
  source:
    type: "Git"
    git:
      uri: "https://github.com/mm-dict/activemq"
      ref: "master"
  strategy:
    type: "Docker"
    dockerStrategy:
  output:
    to:
      kind: "ImageStreamTag"
      name: "activemq:latest"
