kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "activemq-build"
spec:
  runPolicy: "Serial"
  source:
    type: "Git"
    git:
      uri: "https://github.com/ICTO/activemq"
      ref: "5.15.7"
  strategy:
    type: "Docker"
    dockerStrategy:
  output:
    to:
      kind: "ImageStreamTag"
      name: "activemq:5.15.7"
