[template]
prefix = "${CONFD_PREFIX_KEY}"
src = "jetty-realm.properties.tmpl"
dest = "${APP_HOME}/conf/jetty-realm.properties"
mode = "0600"
gid = $GID
uid = $UID
keys = [
  "/config",
  "/users",
  "/admin"
]
